name: Feature Request
description: Suggest an idea for SwiftRPN
title: "[REQUEST]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements to SwiftRPN!
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of SwiftRPN are you using?
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using?
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Is your feature request related to a problem? What's the motivation behind your request?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give a clear and concise description of what change you would like to see.
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Describe any other information or context that relates to this issue.
    validations:
      required: true
